title: Yupana
description: "Распределенная система анализа розничных продаж с открытым исходным кодом"

background: /assets/images/header.jpg

repository: "rusexpertiza-llc/yupana-site"

paginate: 5
paginate_path: "/news/page:num/"

locale: "ru-RU"

author: Yupana, Первый ОФД
github_username: rusexpertiza-llc
twitter_username: yupanaproject
facebook_username: yupanaproject

defaults:
  values:
    layout: post

collections:
  docs:
    output: true
# This will work with Jekyll 4.x
#    sort_by: section

exclude:
  - README
  - vendor
  - Gemfile
  - Dockerfile
  - serve
